---
sidebar: sidebar 
permalink: trident-docker/prereqs-docker.html 
keywords: deploy, astra trident, docker, trident for docker, nfs, iscsi, protcol, nfs protocol, iscsi protocol, configure host, host config 
summary: Astra Trident를 구축하기 전에 호스트에 필수 프로토콜 사전 요구 사항을 설치하고 구성해야 합니다. 
---
= 배포를 위한 사전 요구 사항
:hardbreaks:
:icons: font
:imagesdir: ../media/


Astra Trident를 구축하기 전에 호스트에 필수 프로토콜 사전 요구 사항을 설치하고 구성해야 합니다.

* 배포가 모든 를 충족하는지 확인합니다 link:../trident-get-started/requirements.html["요구 사항"^].
* 지원되는 버전의 Docker가 설치되어 있는지 확인합니다. Docker 버전이 오래되었으면 https://docs.docker.com/engine/install/["설치 또는 업데이트합니다"^].


[listing]
----
docker --version
----
* 프로토콜 사전 요구 사항이 호스트에 설치 및 구성되어 있는지 확인합니다.


[cols="3*"]
|===
| 프로토콜 | 운영 체제 | 명령 


| NFS 를 참조하십시오  a| 
RHEL/CentOS
 a| 
'SUDO yum install -y nfs-utils'



| NFS 를 참조하십시오  a| 
Ubuntu/Debian
 a| 
'UDO apt-get install-y nfs-common'을 선택합니다



| iSCSI  a| 
RHEL/CentOS
 a| 
. 다음 시스템 패키지를 설치합니다.
+
'SUDO yum install -y lsscsi iscsi -initiator-utils sg3_utils device-mapper-multipath'

. 다중 경로 데몬을 시작합니다.
+
'SUDO mpathconf - -enable - -with_multipathd y'

. 'iscsid'와 'multipathd'가 활성화되어 실행되고 있는지 확인합니다.
+
'SUDO systemctl enable iscsid multipathd''SUDO systemctl start iscsid multipathd'

. iSCSI 타겟 검색:
+
'sudo iscsiadm -m discoverydb -t st -p <data_LIF_ip>--discover'

. 검색된 iSCSI 대상에 로그인합니다.
+
'SUDO iscsiadm -m node -p <data_LIF_ip>--login'

. "iSCSI" 활성화 및 시작:
+
'SUDO systemctl enable iscsi''SUDO systemctl start iscsi'를 활성화합니다





| iSCSI  a| 
Ubuntu/Debian
 a| 
. 다음 시스템 패키지를 설치합니다.
+
'SUDO apt-get install-y open-iscsi lsscsg3-utils multipath-tools scitools'

. 다중 경로 설정:
+
'SUDO tee /etc/multipath.conf<-'EOF' 기본값 {user_friendly_names yes find_multipath yes}EOF sudo service multipath-tools restart'입니다

. iscsid와 multipathd가 실행 중인지 확인합니다.
+
'SUDO service open-iscsi start sudo service multipath-tools start'를 참조하십시오

. iSCSI 타겟 검색:
+
'sudo iscsiadm -m discoverydb -t st -p <data_LIF_ip>--discover'

. 검색된 iSCSI 대상에 로그인합니다.
+
'SUDO iscsiadm -m node -p <data_LIF_ip>--login'



|===