---
sidebar: sidebar 
permalink: trident-docker/prereqs-docker.html 
keywords: deploy, astra trident, docker, trident for docker, nfs, iscsi, protcol, nfs protocol, iscsi protocol, configure host, host config 
summary: Astra Trident를 구축하기 전에 호스트에 필수 프로토콜 사전 요구 사항을 설치하고 구성해야 합니다. 
---
= 배포를 위한 사전 요구 사항
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Astra Trident를 구축하기 전에 호스트에 필수 프로토콜 사전 요구 사항을 설치하고 구성해야 합니다.



== 요구 사항을 확인합니다

* 배포가 모든 를 충족하는지 확인합니다 link:../trident-get-started/requirements.html["요구 사항"].
* 지원되는 버전의 Docker가 설치되어 있는지 확인합니다. Docker 버전이 오래되었으면 https://docs.docker.com/engine/install/["설치 또는 업데이트합니다"^].
+
[listing]
----
docker --version
----
* 프로토콜 사전 요구 사항이 호스트에 설치 및 구성되어 있는지 확인합니다.


[cols="3*"]
|===
| 프로토콜 | 운영 체제 | 명령 


| NFS 를 참조하십시오  a| 
RHEL/CentOS 7
 a| 
'SUDO yum install -y nfs-utils'



| NFS 를 참조하십시오  a| 
우분투
 a| 
'UDO apt-get install-y nfs-common'을 선택합니다



| iSCSI  a| 
RHEL/CentOS 7
 a| 
. 다음 시스템 패키지를 설치합니다.
+
'SUDO yum install -y lsscsi iscsi -initiator-utils sg3_utils device-mapper-multipath'

. iscsi-initiator-utils 버전이 6.2.0.874-2.el7 이상인지 확인합니다.
+
rpm -q iscsi-initiator-utils

. 스캔을 수동으로 설정합니다.
+
'SUDO SED-I's/^\(node.session.scan\).*/\1 = manual/'/etc/iscsi/iscsid.conf'

. 다중 경로 설정:
+
'SUDO mpathconf - -enable - -with_multipathd y - -find_multiprohs n'

+

NOTE: etc/multipath.conf에 debrofs 아래에 find_multiprohs no가 포함되어 있는지 확인합니다.

. iscsid와 multipathd가 실행 중인지 확인합니다.
+
'SUDO systemctl enable -- now iscsid multipathd'

. "iSCSI" 활성화 및 시작:
+
'SUDO systemctl enable -- now iscsi'





| iSCSI  a| 
우분투
 a| 
. 다음 시스템 패키지를 설치합니다.
+
'SUDO apt-get install-y open-iscsi lsscsg3-utils multipath-tools scitools'

. open-iscsi 버전이 2.0.874-5ubuntu2.10 이상(bionic) 또는 2.0.874-7.1uubuttu6.1 이상(focal)인지 확인합니다.
+
d패키지-l open-iscsi

. 스캔을 수동으로 설정합니다.
+
'SUDO SED-I's/^\(node.session.scan\).*/\1 = manual/'/etc/iscsi/iscsid.conf'

. 다중 경로 설정:
+
'sudo tee /etc/multipath.conf<-'EOF' 기본값 {user_friendly_names yes find_multipath no} EOF sudo systemctl enable--now multipath-tools.service sudo service multipath-tools restart'입니다

+

NOTE: etc/multipath.conf에 debrofs 아래에 find_multiprohs no가 포함되어 있는지 확인합니다.

. 'open-iscsi'와 'multirpath-tools'가 활성화되어 실행되고 있는지 확인합니다.
+
'SUDO systemctl status multipath -tools''SUDO systemctl enable -- now open-iscsi.service`'SUDO systemctl status open-iscsi'



|===