---
sidebar: sidebar 
permalink: trident-docker/stor-config.html 
keywords: deploy, trident, docker, trident for docker, nfs, iscsi, protocol, nfs protocol, iscsi protocol, configure host, host config, storage config, options, variables, ontap, element, storage pool, cvs, cvs-performance, service type, service level, cloud volumes service, cloud volumes 
summary: Astra Trident 구성에 사용할 수 있는 구성 옵션을 확인하십시오. 
---
= 스토리지 구성 옵션
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Astra Trident 구성에 사용할 수 있는 구성 옵션을 확인하십시오.



== 글로벌 구성 옵션

이러한 구성 옵션은 사용 중인 스토리지 플랫폼에 관계없이 모든 Astra Trident 구성에 적용됩니다.

[cols="3*"]
|===
| 옵션을 선택합니다 | 설명 | 예 


| '내전'  a| 
구성 파일 버전 번호입니다
 a| 
`1`



| 'torageDriverName'입니다  a| 
스토리지 드라이버 이름입니다
 a| 
`ontap-nas`, `ontap-san`, `ontap-nas-economy`,
`ontap-nas-flexgroup`, `solidfire-san`



| '토르agePrefix'  a| 
볼륨 이름에 대한 선택적 접두사입니다. 기본값: `netappdvp_`.
 a| 
`staging_`



| LimitVolumeSize  a| 
볼륨 크기에 대한 선택적 제한. 기본값:""(적용 안 됨)
 a| 
`10g`

|===

TIP: 요소 백엔드에 'toragePrefix'(기본값 포함)를 사용하지 마십시오. 기본적으로 '졸idfire-san' 드라이버는 이 설정을 무시하고 접두어를 사용하지 않습니다. Docker 볼륨 매핑에 특정 tenantID를 사용하거나 이름 문지가 사용된 경우 Docker의 Docker 버전, 드라이버 정보 및 원시 이름으로 채워진 특성 데이터를 사용하는 것이 좋습니다.

생성하는 모든 볼륨에서 기본 옵션을 지정하지 않아도 됩니다. '크기' 옵션은 모든 컨트롤러 유형에 사용할 수 있습니다. 기본 볼륨 크기를 설정하는 방법은 ONTAP 구성 섹션을 참조하십시오.

[cols="3*"]
|===
| 옵션을 선택합니다 | 설명 | 예 


| '크기'입니다  a| 
새 볼륨의 선택적 기본 크기입니다. 기본값: `1G`
 a| 
`10G`

|===


== ONTAP 구성

위의 글로벌 구성 값 외에도 ONTAP를 사용할 경우 다음과 같은 최상위 옵션을 사용할 수 있습니다.

[cols="3*"]
|===
| 옵션을 선택합니다 | 설명 | 예 


| 마나멘타LIF  a| 
ONTAP 관리 LIF의 IP 주소입니다. FQDN(정규화된 도메인 이름)을 지정할 수 있습니다.
 a| 
`10.0.0.1`



| 다타LIF  a| 
프로토콜 LIF의 IP 주소입니다.

* ONTAP NAS 드라이버 *: 지정할 것을 권장합니다 `dataLIF`. 제공되지 않는 경우 Astra Trident는 SVM에서 데이터 LIF를 가져옵니다. NFS 마운트 작업에 사용할 FQDN(정규화된 도메인 이름)을 지정하면 여러 데이터 LIF에서 로드 밸런싱을 위해 라운드 로빈 DNS를 생성할 수 있습니다.

* ONTAP SAN 드라이버 *: iSCSI에 대해 지정하지 마십시오. Astra Trident가 사용합니다 link:https://docs.netapp.com/us-en/ontap/san-admin/selective-lun-map-concept.html["ONTAP 선택적 LUN 맵"^] 다중 경로 세션을 설정하는 데 필요한 iSCI LIF를 검색하려면 경고 발생 시 `dataLIF` 명시적으로 정의됩니다.
 a| 
`10.0.0.2`



| 'VM'입니다  a| 
사용할 스토리지 가상 머신(관리 LIF가 클러스터 LIF인 경우 필요)
 a| 
`svm_nfs`



| '사용자 이름'  a| 
스토리지 디바이스에 접속할 사용자 이름입니다
 a| 
`vsadmin`



| "암호"  a| 
스토리지 디바이스에 연결하는 암호입니다
 a| 
`secret`



| 골재  a| 
프로비저닝을 위한 애그리게이트(선택 사항, SVM에 셋팅해야 하는 경우) ONTAP-NAS-Flexgroup 드라이버의 경우 이 옵션이 무시됩니다. SVM에 할당된 모든 애그리게이트는 FlexGroup 볼륨을 프로비저닝하는 데 사용됩니다.
 a| 
`aggr1`



| 제한선태사용법  a| 
선택 사항으로, 사용량이 이 백분율보다 높을 경우 용량 할당에 실패합니다
 a| 
`75%`



| nfsMountOptions를 선택합니다  a| 
NFS 마운트 옵션을 세밀하게 제어합니다. 기본값은 "-o nfsvers=3"입니다. * ONTAP-NAS 및 ONTAP-NAS-이코노미 드라이버에만 사용 가능 *. https://www.netapp.com/pdf.html?item=/media/10720-tr-4067.pdf["NFS 호스트 구성 정보는 여기 를 참조하십시오"^].
 a| 
`-o nfsvers=4`



| “인명이름”입니다  a| 
Astra Trident는 노드당 작성 및 관리합니다 `igroups` 현재 `netappdvp`.

이 값은 변경하거나 생략할 수 없습니다.

* 에서만 사용할 수 있습니다 `ontap-san` 드라이버 *.
 a| 
`netappdvp`



| LimitVolumeSize  a| 
최대 요청 가능 볼륨 크기 및 qtree 상위 볼륨 크기. * 이 옵션은 'ONTAP-NAS-이코노미' 드라이버의 경우 FlexVol의 크기를 추가로 제한합니다 *.
 a| 
`300g`



| "케트리스퍼플랙스볼륨"  a| 
FlexVol당 최대 qtree는 범위 [50, 300]에 있어야 하며 기본값은 200입니다. * 'ONTAP-NAS-이코노미' 드라이버의 경우 이 옵션을 사용하여 FlexVol*당 최대 qtree 수를 사용자 지정할 수 있습니다.
 a| 
`300`

|===
생성하는 모든 볼륨에 기본 옵션을 지정하지 않아도 됩니다.

[cols="3*"]
|===
| 옵션을 선택합니다 | 설명 | 예 


| '예비공간'  a| 
공간 예약 모드; `none` (씬 프로비저닝됨) 또는 을 클릭합니다 `volume` (두꺼운)
 a| 
"없음"



| 냅샷정책  a| 
사용할 스냅샷 정책이며 기본값은 입니다 `none`
 a| 
"없음"



| 안산예비역  a| 
스냅숏 예비 공간 비율, 기본값은 ""이며 ONTAP 기본값을 사용합니다
 a| 
`10`



| 'plitOnClone'을 선택합니다  a| 
생성 시 상위 클론에서 클론을 분할합니다. 기본값은 입니다 `false`
 a| 
거짓입니다



| 암호화  a| 
새 볼륨에 NVE(NetApp Volume Encryption)를 지원하며 기본값은 'false'입니다. 이 옵션을 사용하려면 NVE 라이센스가 클러스터에서 활성화되어 있어야 합니다.

백엔드에서 NAE가 활성화된 경우 Astra Trident에 프로비저닝된 모든 볼륨은 NAE가 활성화됩니다.

자세한 내용은 다음을 참조하십시오. link:../trident-reco/security-reco.html["Astra Trident가 NVE 및 NAE와 연동되는 방식"].
 a| 
참



| 유니크권한  a| 
프로비저닝된 NFS 볼륨에 대한 NAS 옵션, 기본값은 로 설정됩니다 `777`
 a| 
`777`



| 나프산디렉토리  a| 
에 액세스하기 위한 NAS 옵션입니다 `.snapshot` Directory(디렉터리), 기본값 `false`
 a| 
"참"입니다



| 엑포트정책  a| 
NFS 엑스포트 정책에서 사용할 NAS 옵션이며 기본값은 입니다 `default`
 a| 
`default`



| '생태성 스타일'을 참조하십시오  a| 
프로비저닝된 NFS 볼륨에 액세스하기 위한 NAS 옵션입니다.

NFS를 지원합니다 `mixed` 및 `unix` 보안 스타일. 기본값은 입니다 `unix`.
 a| 
`unix`



| 파일 시스템 유형  a| 
SAN 옵션 - 파일 시스템 유형을 선택합니다. 기본값은 입니다 `ext4`
 a| 
`xfs`



| '계층화 정책'  a| 
사용할 계층화 정책, 기본값은 입니다 `none`; `snapshot-only` ONTAP 9.5 이전 SVM-DR 구성용
 a| 
"없음"

|===


=== 축척 옵션

ONTAP-NAS와 ONTAP-SAN 드라이버는 각 Docker 볼륨에 대해 ONTAP FlexVol를 생성합니다. ONTAP는 최대 12,000개의 FlexVol 클러스터를 사용하여 클러스터 노드당 최대 1,000개의 FlexVol을 지원합니다. Docker 볼륨 요구 사항이 이러한 제한 범위 내에 있을 경우 Docker 볼륨 세부 스냅샷 및 클론 복제와 같은 FlexVol에서 제공되는 추가 기능 때문에 'ONTAP-NAS' 드라이버가 선호되는 NAS 솔루션입니다.

FlexVol에 허용 가능한 것보다 더 많은 Docker 볼륨이 필요한 경우 ONTAP-NAS-이코노미 또는 ONTAP-SAN-이코노미 드라이버를 선택합니다.

'ONTAP-NAS-이코노미' 드라이버는 자동으로 관리되는 FlexVol 풀 내에 ONTAP qtree로 Docker 볼륨을 생성합니다. qtree는 일부 기능을 희생하여 클러스터 노드당 최대 100,000 및 클러스터당 2,400,000까지 훨씬 더 뛰어난 확장을 제공합니다. 'ONTAP-NAS-G경제적인' 드라이버는 Docker 볼륨의 세분화된 스냅샷 또는 클론 복제를 지원하지 않습니다.


NOTE: Swarm은 여러 노드에서 볼륨 생성을 조율하지 않으므로 현재 Docker Swarm에서 ONTAP-NAS-이코노미 드라이버가 지원되지 않습니다.

ONTAP-SAN-이코노미 드라이버는 자동으로 관리되는 FlexVol의 공유 풀 내에 Docker 볼륨을 ONTAP LUN으로 생성합니다. 이렇게 하면 각 FlexVol가 하나의 LUN에만 제한되지 않으며 SAN 워크로드에 더 나은 확장성을 제공합니다. 스토리지 시스템에 따라 ONTAP는 클러스터당 최대 16384개의 LUN을 지원합니다. 볼륨이 그 아래에 LUN이 있으므로 이 드라이버는 Docker 볼륨 세부 스냅샷 및 클론 복제를 지원합니다.

수십 억 개의 파일로 구성된 페타바이트 용량으로 확장할 수 있는 단일 볼륨의 병렬 처리를 늘리려면 ONTAP-NAS-Flexgroup 드라이버를 선택하십시오. FlexGroups의 이상적인 사용 사례로는 AI/ML/DL, 빅데이터 및 분석, 소프트웨어 빌드, 스트리밍, 파일 저장소 등이 있습니다. Trident는 FlexGroup 볼륨을 프로비저닝할 때 SVM에 할당된 모든 애그리게이트를 사용합니다. Trident의 FlexGroup 지원에도 다음과 같은 고려 사항이 있습니다.

* ONTAP 버전 9.2 이상이 필요합니다.
* 이번 작부터 FlexGroups는 NFS v3만 지원합니다.
* SVM에 대해 64비트 NFSv3 식별자를 사용하는 것이 좋습니다.
* 최소 권장 FlexGroup 크기는 100GB입니다.
* FlexGroup 볼륨에 대해서는 클론 생성이 지원되지 않습니다.


FlexGroups에 적합한 FlexGroups 및 워크로드에 대한 자세한 내용은 를 참조하십시오 https://www.netapp.com/pdf.html?item=/media/12385-tr4571pdf.pdf["NetApp FlexGroup 볼륨 모범 사례 및 구현 가이드 를 참조하십시오"^].

같은 환경에서 고급 기능과 대규모 확장을 위해 ONTAP-NAS를 사용하는 Docker Volume Plugin과 ONTAP-NAS-E경제적인 인스턴스를 여러 개 실행할 수 있습니다.



=== ONTAP 구성 파일의 예

* 'ONTAP-NAS' 드라이버용 NFS 예 *

[listing]
----
{
    "version": 1,
    "storageDriverName": "ontap-nas",
    "managementLIF": "10.0.0.1",
    "dataLIF": "10.0.0.2",
    "svm": "svm_nfs",
    "username": "vsadmin",
    "password": "password",
    "aggregate": "aggr1",
    "defaults": {
      "size": "10G",
      "spaceReserve": "none",
      "exportPolicy": "default"
    }
}
----
* 'ONTAP-NAS-Flexgroup' 드라이버의 NFS 예 *

[listing]
----
{
    "version": 1,
    "storageDriverName": "ontap-nas-flexgroup",
    "managementLIF": "10.0.0.1",
    "dataLIF": "10.0.0.2",
    "svm": "svm_nfs",
    "username": "vsadmin",
    "password": "password",
    "defaults": {
      "size": "100G",
      "spaceReserve": "none",
      "exportPolicy": "default"
    }
}
----
* 'ONTAP-NAS-이코노미' 드라이버용 NFS 예 *

[listing]
----
{
    "version": 1,
    "storageDriverName": "ontap-nas-economy",
    "managementLIF": "10.0.0.1",
    "dataLIF": "10.0.0.2",
    "svm": "svm_nfs",
    "username": "vsadmin",
    "password": "password",
    "aggregate": "aggr1"
}
----
* 'ONTAP-SAN' 드라이버용 iSCSI 예 *

[listing]
----
{
    "version": 1,
    "storageDriverName": "ontap-san",
    "managementLIF": "10.0.0.1",
    "dataLIF": "10.0.0.3",
    "svm": "svm_iscsi",
    "username": "vsadmin",
    "password": "password",
    "aggregate": "aggr1",
    "igroupName": "netappdvp"
}
----
* 'ONTAP-SAN-이코노미' 드라이버용 NFS 예시 *

[listing]
----
{
    "version": 1,
    "storageDriverName": "ontap-san-economy",
    "managementLIF": "10.0.0.1",
    "dataLIF": "10.0.0.3",
    "svm": "svm_iscsi_eco",
    "username": "vsadmin",
    "password": "password",
    "aggregate": "aggr1",
    "igroupName": "netappdvp"
}
----


== Element 소프트웨어 구성

Element 소프트웨어(NetApp HCI/SolidFire)를 사용하는 경우 글로벌 구성 값 외에도 이러한 옵션을 사용할 수 있습니다.

[cols="3*"]
|===
| 옵션을 선택합니다 | 설명 | 예 


| 끝점  a| 
https://<login>:<password>@<mvip>/json-rpc/<element-version> 으로 문의하십시오
 a| 
https://admin:admin@192.168.160.3/json-rpc/8.0 으로 문의하십시오



| 'VIP'  a| 
iSCSI IP 주소 및 포트
 a| 
10.0.0.7:3260



| 테난트이름  a| 
사용할 SolidFireF 테넌트(찾을 수 없는 경우 생성됨)
 a| 
`docker`



| 이니토IFace  a| 
iSCSI 트래픽을 기본 인터페이스가 아닌 인터페이스로 제한할 때 인터페이스를 지정합니다
 a| 
`default`



| '유형'  a| 
QoS 사양
 a| 
아래 예를 참조하십시오



| 레가시NamePrefix  a| 
업그레이드된 Trident 설치의 접두사 1.3.2 이전 버전의 Trident를 사용하고 기존 볼륨으로 업그레이드를 수행하는 경우 볼륨 이름 방법을 통해 매핑된 이전 볼륨에 액세스하려면 이 값을 설정해야 합니다.
 a| 
`netappdvp-`

|===
졸idfire-san 드라이버는 Docker Swarm을 지원하지 않습니다.



=== Element 소프트웨어 구성 파일의 예

[listing]
----
{
    "version": 1,
    "storageDriverName": "solidfire-san",
    "Endpoint": "https://admin:admin@192.168.160.3/json-rpc/8.0",
    "SVIP": "10.0.0.7:3260",
    "TenantName": "docker",
    "InitiatorIFace": "default",
    "Types": [
        {
            "Type": "Bronze",
            "Qos": {
                "minIOPS": 1000,
                "maxIOPS": 2000,
                "burstIOPS": 4000
            }
        },
        {
            "Type": "Silver",
            "Qos": {
                "minIOPS": 4000,
                "maxIOPS": 6000,
                "burstIOPS": 8000
            }
        },
        {
            "Type": "Gold",
            "Qos": {
                "minIOPS": 6000,
                "maxIOPS": 8000,
                "burstIOPS": 10000
            }
        }
    ]
}
----