---
sidebar: sidebar 
permalink: trident-docker/upgrade-uninstall-docker.html 
keywords: uninstall, astra trident, trident for docker, docker, upgrade trident for docker 
summary: 사용 중인 볼륨에 영향을 주지 않고 Docker용 Astra Trident를 안전하게 업그레이드할 수 있습니다. 업그레이드 프로세스 중에는 플러그인에서 지시하는 docker volume 명령이 성공하지 못하는 짧은 기간이 있으며 플러그인이 다시 실행될 때까지 응용 프로그램에서 볼륨을 마운트할 수 없습니다. 대부분의 경우 몇 초 이내에 완료됩니다. 
---
= Astra Trident를 업그레이드하거나 제거합니다
:hardbreaks:
:icons: font
:imagesdir: ../media/


사용 중인 볼륨에 영향을 주지 않고 Docker용 Astra Trident를 안전하게 업그레이드할 수 있습니다. 업그레이드 프로세스 중에는 플러그인에서 지시하는 docker volume 명령이 성공하지 못하는 짧은 기간이 있으며 플러그인이 다시 실행될 때까지 응용 프로그램에서 볼륨을 마운트할 수 없습니다. 대부분의 경우 몇 초 이내에 완료됩니다.



== 업그레이드

Docker를 위한 Astra Trident를 업그레이드하려면 다음 단계를 수행하십시오.

.단계
. 기존 볼륨 나열:
+
[listing]
----
docker volume ls
DRIVER              VOLUME NAME
netapp:latest       my_volume
----
. 플러그인 비활성화:
+
[listing]
----
docker plugin disable -f netapp:latest
docker plugin ls
ID                  NAME                DESCRIPTION                          ENABLED
7067f39a5df5        netapp:latest       nDVP - NetApp Docker Volume Plugin   false
----
. 플러그인 업그레이드:
+
[listing]
----
docker plugin upgrade --skip-remote-check --grant-all-permissions netapp:latest netapp/trident-plugin:21.07
----
+

NOTE: Astra Trident의 18.01 릴리스는 nDVP를 대체합니다. 'NetApp/ndvp-plugin' 이미지에서 'NetApp/트리덴트 - 플러그인' 이미지로 직접 업그레이드해야 합니다.

. 플러그인 활성화:
+
[listing]
----
docker plugin enable netapp:latest
----
. 플러그인이 활성화되어 있는지 확인합니다.
+
[listing]
----
docker plugin ls
ID                  NAME                DESCRIPTION                             ENABLED
7067f39a5df5        netapp:latest       Trident - NetApp Docker Volume Plugin   true
----
. 볼륨이 표시되는지 확인합니다.
+
[listing]
----
docker volume ls
DRIVER              VOLUME NAME
netapp:latest       my_volume
----
+

IMPORTANT: Astra Trident(20.10 이전)의 이전 버전에서 Astra Trident 20.10 이상으로 업그레이드하는 경우 오류가 발생할 수 있습니다. 자세한 내용은 을 참조하십시오 link:known-issues-docker.html["알려진 문제"^]. 오류가 발생하면 먼저 플러그인을 비활성화하고 플러그인을 제거한 다음 추가 구성 매개 변수 "docker plugin install NetApp/trident-plugin:20.10 -- alias NetApp --grant-all-permissions config=config.json"을 전달하여 필요한 Astra Trident 버전을 설치해야 합니다





== 설치 제거

Docker용 Astra Trident를 제거하려면 다음 단계를 수행하십시오.

.단계
. 플러그인이 생성한 모든 볼륨을 제거합니다.
. 플러그인 비활성화:
+
[listing]
----
docker plugin disable netapp:latest
docker plugin ls
ID                  NAME                DESCRIPTION                          ENABLED
7067f39a5df5        netapp:latest       nDVP - NetApp Docker Volume Plugin   false
----
. 플러그인 제거:
+
[listing]
----
docker plugin rm netapp:latest
----

