---
sidebar: sidebar 
permalink: trident-managing-k8s/uninstall-trident.html 
keywords: uninstall, astra trident, methods, operator, tridentctl, helm 
summary: Astra Trident의 설치 방식에 따라 여러 옵션을 사용하여 제거할 수 있습니다. 
---
= Astra Trident를 제거합니다
:hardbreaks:
:icons: font
:imagesdir: ../media/


Astra Trident의 설치 방식에 따라 여러 옵션을 사용하여 제거할 수 있습니다.



== Helm을 사용하여 제거합니다

Helm을 사용하여 Astra Trident를 설치한 경우 'helm uninstall'을 사용하여 제거할 수 있습니다.

[listing]
----
#List the Helm release corresponding to the Astra Trident install.
$ helm ls -n trident
NAME          NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                           APP VERSION
trident       trident         1               2021-04-20 00:26:42.417764794 +0000 UTC deployed        trident-operator-21.07.1        21.07.1

#Uninstall Helm release to remove Trident
$ helm uninstall trident -n trident
release "trident" uninstalled
----


== Trident 연산자를 사용하여 제거합니다

운영자를 사용하여 Astra Trident를 설치한 경우 다음 중 하나를 수행하여 제거할 수 있습니다.

* ** 제거 플래그를 설정하려면 '트리젠터레이터'를 편집하여 '트리젠터레이터'를 편집하고 'Spec.uninstall=true'를 설정할 수 있습니다. 다음 그림과 같이 '트리엔오케스트레이터' CR을 편집하고 '제거' 플래그를 설정합니다.
+
[listing]
----
$  kubectl patch torc <trident-orchestrator-name> --type=merge -p '{"spec":{"uninstall":true}}'
----
+
'uninstall' 플래그가 'true'로 설정되어 있으면 Trident 운영자가 Trident를 제거하지만 Trident 자체 자체를 제거하지 않습니다. Trident를 다시 설치하려면 해당 Trident를 정리하고 새 AgentOrchestrator를 생성해야 합니다.

* ** "트리펜터레이터" 삭제: ** Astra Trident를 배포하는 데 사용된 '트리엔오케스트레이터' CR을 제거하여 운영자에게 Trident를 제거하도록 지시합니다. 운영자는 '트리펜터레이터'의 제거를 처리하고 Astra Trident 구축 및 디포드를 제거하여 설치의 일부로 생성한 Trident 포드를 삭제합니다. Astra Trident(CRD 생성 포함)를 완전히 제거하고 슬레이트 클린을 효과적으로 닦기 위해 '트리펜터레이터'를 편집하여 '와이프아웃' 옵션을 통과할 수 있습니다. 다음 예를 참조하십시오.


[listing]
----
$ kubectl patch torc <trident-orchestrator-name> --type=merge -p '{"spec":{"wipeout":["crds"],"uninstall":true}}'
----
그러면 Astra Trident가 완전히 설치 제거되며, 백엔드 및 관리하는 볼륨과 관련된 모든 메타데이터가 지워집니다. 이후 설치는 새로 설치하는 것으로 처리됩니다.


WARNING: 전체 제거를 수행할 때에만 CRD를 지우는 것을 고려해야 합니다. 이 작업은 취소할 수 없습니다. ** 처음부터 새로 Astra Trident 설치를 생성하기 위해 사용하지 않는 한 CRD를 지우지 마십시오**.



== tridentctl을 사용하여 제거합니다

다음과 같이 tridentctl에서 'uninstall' 명령을 실행하면 CRD 및 관련 객체를 제외한 Astra Trident와 관련된 모든 리소스가 제거되므로 설치 프로그램을 다시 쉽게 실행하여 최신 버전으로 업데이트할 수 있습니다.

[listing]
----
./tridentctl uninstall -n <namespace>
----
Astra Trident를 완전히 제거하려면 Astra Trident에서 생성한 CRD의 종료자를 제거하고 CRD를 삭제해야 합니다.
