---
sidebar: sidebar 
permalink: trident-use/automatic-workernode.html 
keywords: beta feature, trident, automatic worker node, worker node prep, preparation, NFS, iSCSI 
summary: Astra Trident는 Kubernetes 클러스터에 있는 노드에 필요한 NFS 및 iSCSI 툴을 자동으로 설치할 수 있습니다. 
---
= 작업자 노드 자동 준비
:hardbreaks:
:icons: font
:imagesdir: ../media/


Astra Trident는 Kubernetes 클러스터에 있는 노드에 필요한 NFS 및 iSCSI 툴을 자동으로 설치할 수 있습니다. 이것은 * 베타 기능 * 이며 * 프로덕션 클러스터용으로 * 제공되지 않습니다. 현재 이 기능은 * CentOS, RHEL 및 Ubuntu * 를 실행하는 노드에 사용할 수 있습니다.

이 기능을 위해 Astra Trident는 tridentctl을 사용하여 배포된 설치를 위한 '--enable-node-prep'라는 새로운 설치 플래그를 포함합니다. Trident 연산자가 있는 배포의 경우 부울 옵션 "enableNodePrep"을 사용합니다.


WARNING: '--enable-node-prep' 설치 옵션은 Astra Trident가 볼륨을 작업자 노드에 마운트할 때 NFS 및 iSCSI 패키지 및/또는 서비스가 실행 중인지 설치 및 확인하도록 지시합니다. 이 기능은 개발/테스트 환경에서 사용할 수 있도록 고안된 * 베타 기능 * 으로, 운영용으로 * 검증되지 않았습니다.

tridentctl로 배포된 Astra Trident 설치에 '--enable-node-prep' 플래그가 포함된 경우 다음 작업이 수행됩니다.

. 설치의 일부로, Astra Trident가 실행되는 노드를 등록합니다.
. 영구 볼륨 클레임(PVC) 요청이 이루어지면 Astra Trident는 관리하는 백엔드 중 하나에서 PV를 생성합니다.
. POD에서 PVC를 사용하려면 POD가 실행되는 노드에 볼륨을 마운트하기 위해 Astra Trident가 필요합니다. Astra Trident는 필요한 NFS/iSCSI 클라이언트 유틸리티를 설치하고 필요한 서비스가 활성 상태인지 확인합니다. 볼륨이 마운트되기 전에 이 작업이 수행됩니다.


작업자 노드의 준비는 볼륨을 마운트하려는 첫 번째 시도의 일부로 한 번만 수행됩니다. Astra Trident 외부의 변경 사항이 NFS와 iSCSI 유틸리티에 닿지 않는 한 이후의 모든 볼륨 마운트는 성공해야 합니다.

이러한 방법으로 Astra Trident는 Kubernetes 클러스터의 모든 노드에 볼륨을 마운트 및 연결하는 데 필요한 유틸리티가 있는지 확인할 수 있습니다. NFS 볼륨의 경우 내보내기 정책에서도 볼륨을 마운트할 수 있어야 합니다. Trident는 백엔드별로 엑스포트 정책을 자동으로 관리할 수도 있고, 사용자는 대역 외 엑스포트 정책을 관리할 수도 있습니다.
