---
sidebar: sidebar 
permalink: trident-use/backend_ops_kubectl.html 
keywords: backends, storage system, anf, cvs for aws, cvs for gcp, element, hci, solidfire, ontap, aff, fas, ontap select, configure backends, kubectl, create backends, delete backends, update backends, view backends 
summary: kubbtl을 사용하여 백엔드 관리 작업을 수행하는 방법에 대해 알아보십시오. 
---
= kubeck을 사용하여 백엔드 관리 수행
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


kubbtl을 사용하여 백엔드 관리 작업을 수행하는 방법에 대해 알아보십시오.



== 백엔드를 삭제합니다

'트리멘BackendConfig'를 삭제하면 Astra Trident가 백엔드 삭제/보존('정책' 기준)을 수행하도록 지시합니다. 백엔드를 삭제하려면 deletionPolicy가 delete로 설정되어 있는지 확인합니다. 트리젠백엔드구성만 삭제하려면, '정책'이 '유지'로 설정되어 있는지 확인하십시오. 이렇게 하면 백엔드가 계속 존재하고 'tridentctl'을 사용하여 관리할 수 있습니다.

다음 명령을 실행합니다.

[listing]
----
$ kubectl delete tbc <tbc-name> -n trident
----
Astra Trident는 트리엔엔드구성에서 사용 중인 Kubernetes 비밀을 삭제하지 않습니다. Kubernetes 사용자는 기밀을 정해야 합니다. 비밀 정보를 삭제할 때는 주의해야 합니다. 암호는 백엔드에서 사용하지 않는 경우에만 삭제해야 합니다.



== 기존 백엔드를 봅니다

다음 명령을 실행합니다.

[listing]
----
$ kubectl get tbc -n trident
----
또한 'tridentctl get backend-n trident' 또는 'tridentctl get backend-o YAML-n trident'를 실행하여 존재하는 모든 백엔드 목록을 확인할 수 있습니다. 이 목록에는 tridentctl로 만든 백엔드 또한 포함됩니다.



== 백엔드를 업데이트합니다

백엔드를 업데이트해야 하는 이유는 여러 가지가 있을 수 있습니다.

* 스토리지 시스템에 대한 자격 증명이 변경되었습니다. 자격 증명을 업데이트하려면 '트리펜엔드구성' 객체에 사용되는 Kubernetes Secret를 업데이트해야 합니다. Astra Trident가 자동으로 백엔드를 제공된 최신 자격 증명으로 업데이트합니다. 다음 명령을 실행하여 Kubernetes Secret를 업데이트하십시오.


[listing]
----
$ kubectl apply -f <updated-secret-file.yaml> -n trident
----
* 매개 변수(예: 사용 중인 ONTAP SVM의 이름)를 업데이트해야 합니다. 이 경우 Kubernetes를 통해 '트리펜엔드구성' 객체를 직접 업데이트할 수 있습니다.


[listing]
----
$ kubectl apply -f <updated-backend-file.yaml>
----
또는 다음 명령을 실행하여 기존 '트리엔백엔드구성' CR을 변경합니다.

[listing]
----
$ kubectl edit tbc <tbc-name> -n trident
----
백엔드 업데이트에 실패하면 백엔드는 마지막으로 알려진 구성으로 계속 유지됩니다. 'kubtl get tbc<tbc-name>-o YAML-n trident' 또는 'kubtl t설명해 tbc<tbc-name>-n trident'를 실행하여 로그를 보고 원인을 확인할 수 있습니다.

구성 파일의 문제를 확인하고 수정한 후 update 명령을 다시 실행할 수 있습니다.
