---
sidebar: sidebar 
permalink: trident-use/trident-fsx.html 
keywords: Amazon FSx for NetApp ONTAP, FSx for ONTAP, deploy Trident, integrate Trident, Trident 
summary: 'NetApp ONTAP용 Amazon FSx와 Astra Trident를 사용하면 Amazon EKS(Elastic Kubernetes Service)에서 실행되는 Kubernetes 클러스터가 ONTAP에서 지원하는 블록 및 파일 영구 볼륨을 프로비저닝할 수 있습니다.' 
---
= NetApp ONTAP용 Amazon FSx와 함께 Astra Trident를 사용하십시오
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/what-is-fsx-ontap.html["NetApp ONTAP용 Amazon FSx"^] NetApp ONTAP 스토리지 운영 체제가 제공하는 파일 시스템을 실행하고 실행할 수 있도록 완벽하게 관리되는 AWS 서비스입니다. ONTAP용 FSX를 사용하면 익숙한 NetApp 기능, 성능 및 관리 기능을 활용하는 동시에, AWS에 데이터를 저장하는 데 따른 단순성, 민첩성, 보안, 확장성을 활용할 수 있습니다. ONTAP용 FSX는 ONTAP 파일 시스템 기능 및 관리 API를 지원합니다.



== 개요

파일 시스템은 Amazon FSx의 주요 리소스이며, 이는 사내 ONTAP 클러스터와 유사합니다. 각 SVM 내에서 파일 시스템에 파일과 폴더를 저장하는 데이터 컨테이너인 하나 이상의 볼륨을 생성할 수 있습니다. NetApp ONTAP용 Amazon FSx를 사용하면 클라우드에서 Data ONTAP가 관리형 파일 시스템으로 제공됩니다. 새로운 파일 시스템 유형을 * NetApp ONTAP * 라고 합니다.

NetApp ONTAP용 Amazon FSx와 Astra Trident를 사용하면 Amazon EKS(Elastic Kubernetes Service)에서 실행되는 Kubernetes 클러스터가 ONTAP에서 지원하는 블록 및 파일 영구 볼륨을 프로비저닝할 수 있습니다.



== 고려 사항

* SMB 볼륨:
+
** SMB 볼륨은 를 사용하여 지원됩니다 `ontap-nas` 드라이버만 해당.
** Astra Trident EKS 애드온에서는 SMB 볼륨이 지원되지 않습니다.
** Astra Trident는 Windows 노드에서 실행되는 Pod에만 마운트된 SMB 볼륨을 지원합니다.


* Astra Trident 24.02 이전에는 자동 백업이 활성화된 Amazon FSx 파일 시스템에서 생성된 볼륨을 Trident에서 삭제할 수 없었습니다. Astra Trident 24.02 이상에서 이 문제를 방지하려면 를 지정합니다 `fsxFilesystemID`있습니다 `apiRegion`있습니다 `apikey`있습니다 `secretKey` AWS FSx for ONTAP의 백엔드 구성 파일에 있습니다.
+

NOTE: Astra Trident에 IAM 역할을 지정하는 경우 를 지정하는 것을 생략할 수 있습니다 `apiRegion`, `apiKey`, 및 `secretKey` 필드를 Astra Trident로 명시적으로 전환합니다. 자세한 내용은 을 참조하십시오 link:../trident-use/trident-fsx-examples.html["ONTAP 구성 옵션 및 예제용 FSX"].





== FSx for ONTAP 드라이버 세부 정보

다음 드라이버를 사용하여 Astra Trident를 NetApp ONTAP용 Amazon FSx와 통합할 수 있습니다.

* 'ONTAP-SAN': 프로비저닝되는 각 PV는 NetApp ONTAP 볼륨용 자체 Amazon FSx 내에 있는 LUN입니다.
* 'ONTAP-SAN-이코노미': 프로비저닝되는 각 PV는 NetApp ONTAP 볼륨에 대해 Amazon FSx당 구성 가능한 LUN 수를 가진 LUN입니다.
* ONTAP-NAS: 프로비저닝되는 각 PV는 NetApp ONTAP 볼륨용 전체 Amazon FSx입니다.
* 'ONTAP-NAS-E경제적인': 각 PV 프로비저닝은 qtree이며, NetApp ONTAP 볼륨에 대해 Amazon FSx당 qtree를 구성할 수 있습니다.
* 'ONTAP-NAS-flexgroup': 프로비저닝되는 각 PV는 NetApp ONTAP FlexGroup 볼륨에 대한 전체 Amazon FSx입니다.


드라이버에 대한 자세한 내용은 을 참조하십시오 link:../trident-use/ontap-nas.html["NAS 드라이버"] 및 link:../trident-use/ontap-san.html["SAN 드라이버"].



== 인증

Astra Trident는 두 가지 인증 모드를 제공합니다.

* 인증서 기반: Astra Trident는 SVM에 설치된 인증서를 사용하여 FSx 파일 시스템의 SVM과 통신합니다.
* 자격 증명 기반: 파일 시스템에 대해 'fsxadmin' 사용자를 사용하거나 SVM용으로 구성된 'vsadmin' 사용자를 사용할 수 있습니다.
+

WARNING: Astra Trident는 한 대로 실행될 것으로 예상합니다 `vsadmin` SVM 사용자 또는 동일한 역할을 가진 다른 이름의 사용자 NetApp ONTAP용 Amazon FSx에는 가 있습니다 `fsxadmin` ONTAP의 제한된 교체인 사용자입니다 `admin` 클러스터 사용자. 을 사용하는 것이 좋습니다 `vsadmin` Astra Trident와 함께.



자격 증명 기반 방법과 인증서 기반 방법 간에 이동하도록 백엔드를 업데이트할 수 있습니다. 그러나 * 자격 증명 및 인증서 * 를 제공하려고 하면 백엔드 생성이 실패합니다. 다른 인증 방법으로 전환하려면 백엔드 구성에서 기존 방법을 제거해야 합니다.

인증 활성화에 대한 자세한 내용은 드라이버 유형에 대한 인증을 참조하십시오.

* link:ontap-nas-prep.html["ONTAP NAS 인증"]
* link:ontap-san-prep.html["ONTAP SAN 인증"]




== EKS용 클라우드 ID

클라우드 ID를 사용하면 Kubernetes Pod에서 명시적 AWS 자격 증명을 제공하지 않고 AWS IAM 역할로 인증하여 AWS 리소스에 액세스할 수 있습니다.

AWS에서 클라우드 ID를 활용하려면 다음이 필요합니다.

* EKS를 사용하여 구축된 Kubernetes 클러스터
* 가 포함된 Astra Trident가 설치되었습니다 `cloudProvider` 지정 `"AWS"` 및 `cloudIdentity` AWS IAM 역할 지정
+
[role="tabbed-block"]
====
.Trident 운영자
--
Trident 연산자를 사용하여 Astra Trident를 설치하려면 편집을 진행합니다 `tridentorchestrator_cr.yaml` 를 눌러 설정합니다 `cloudProvider` 를 선택합니다 `"AWS"` 그리고 설정합니다 `cloudIdentity` AWS IAM 역할로 이동합니다.

예를 들면 다음과 같습니다.

[listing]
----
apiVersion: trident.netapp.io/v1
kind: TridentOrchestrator
metadata:
  name: trident
spec:
  debug: true
  namespace: trident
  imagePullPolicy: IfNotPresent
  cloudProvider: "AWS"
  cloudIdentity: "'eks.amazonaws.com/role-arn: arn:aws:iam::123456:role/astratrident-role'"
----
--
.헬름
--
다음 환경 변수를 사용하여 * 클라우드 공급자 * 및 * 클라우드 ID * 플래그의 값을 설정합니다.

`export CP="AWS"`
`export CI="'eks.amazonaws.com/role-arn: arn:aws:iam::123456:role/astratrident-role'"`

다음 예에서는 Astra Trident 및 Sets를 설치합니다 `cloudProvider` 를 선택합니다 `AWS` 환경 변수를 사용합니다 `$CP` 및 환경 변수를 사용하여 'cloudIdentity'를 설정합니다 `$CI`:

[listing]
----
helm install trident trident-operator-100.2402.0.tgz --set cloudProvider=$CP --set cloudIdentity=$CI
----
--
.<code>tridentctl</code>
--
다음 환경 변수를 사용하여 * 클라우드 공급자 * 및 * 클라우드 ID * 플래그의 값을 설정합니다.

`export CP="AWS"`
`export CI="'eks.amazonaws.com/role-arn: arn:aws:iam::123456:role/astratrident-role'"`

다음 예에서는 Astra Trident를 설치하고 를 설정합니다 `cloud-provider` 에 플래그 지정 `$CP`, 및 `cloud-identity` 를 선택합니다 `$CI`:

[listing]
----
tridentctl install --cloud-provider=$CP --cloud-identity="$CI" -n trident
----
--
====




== 자세한 내용을 확인하십시오

* https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/what-is-fsx-ontap.html["NetApp ONTAP용 Amazon FSx 문서"^]
* https://www.netapp.com/blog/amazon-fsx-for-netapp-ontap/["NetApp ONTAP용 Amazon FSx 블로그 게시물"^]

