---
sidebar: sidebar 
permalink: trident-get-started/intro.html 
keywords: product overview, astra trident, fsx, element, astra, google cloud, cvs, architecture, test drive, node pod, controller pod, pods, csi, sidecar 
summary: 'Astra Trident는 NetApp이 Astra 제품군의 일부로 유지 관리하는 완전히 지원되는 오픈 소스 프로젝트입니다. CSI(Container Storage Interface)와 같은 업계 표준 인터페이스를 사용하여 컨테이너식 애플리케이션의 지속성 요구 사항을 충족하도록 설계되었습니다.' 
---
= Astra Trident에 대해 자세히 알아보십시오
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Astra Trident는 NetApp이 의 일부로 관리하며 완벽한 지원이 제공되는 오픈 소스 프로젝트입니다 link:https://docs.netapp.com/us-en/astra-family/intro-family.html["Astra 제품군"^]. CSI(Container Storage Interface)와 같은 업계 표준 인터페이스를 사용하여 컨테이너식 애플리케이션의 지속성 요구 사항을 충족하도록 설계되었습니다.



== 아스트라(Astra)란?

Astra를 사용하면 퍼블릭 클라우드와 온프레미스 모두에서 Kubernetes에서 실행되는 데이터 기반의 컨테이너 워크로드를 손쉽게 관리, 보호 및 이동할 수 있습니다.

Astra는 Astra Trident를 기반으로 영구 컨테이너 스토리지를 프로비저닝하고 제공합니다. 또한 스냅샷, 백업 및 복원, 활동 로그, 데이터 보호를 위한 활성 클론 복제, 재해/데이터 복구, 데이터 감사, Kubernetes 워크로드를 위한 마이그레이션 사용 사례와 같은 고급 애플리케이션 인식 데이터 관리 기능도 제공합니다.

에 대해 자세히 알아보십시오 link:https://bluexp.netapp.com/astra["Astra 또는 무료 평가판에 등록하십시오"^].



== Astra Trident란?

Astra Trident를 사용하면 ONTAP(AFF, NetApp FAS, Select, 클라우드, NetApp ONTAP용 Amazon FSx), Element 소프트웨어(NetApp HCI, SolidFire), Azure NetApp Files 서비스 및 Google Cloud 기반 Cloud Volumes Service

Astra Trident는 기본적으로 와 통합되는 CSI(컨테이너 스토리지 인터페이스) 호환 동적 스토리지 오케스트레이터입니다 link:https://kubernetes.io/["쿠버네티스"^]. Astra Trident는 클러스터의 각 작업자 노드에서 단일 컨트롤러 Pod와 노드 Pod로 실행됩니다. 을 참조하십시오 link:../trident-get-started/architecture.html["Astra Trident 아키텍처"] 를 참조하십시오.

또한 Astra Trident는 NetApp 스토리지 플랫폼을 위한 Docker 에코시스템과의 직접 통합을 제공합니다. NetApp Docker 볼륨 플러그인(nDVP)은 스토리지 플랫폼에서 Docker 호스트로 스토리지 리소스를 프로비저닝 및 관리할 수 있도록 지원합니다. 을 참조하십시오 link:../trident-docker/deploy-docker.html["Docker를 위한 Astra Trident 구축"] 를 참조하십시오.


NOTE: Kubernetes를 처음으로 사용하는 경우라면 에 익숙해야 합니다 link:https://kubernetes.io/docs/home/["Kubernetes 개념 및 툴"^].



== Astra Trident 시험 구동을 시작하십시오

시험 구동을 실시하려면 "컨테이너식 워크로드용 영구 스토리지를 간편하게 배포 및 복제" 액세스 권한을 요청하십시오. link:https://www.netapp.com/us/try-and-buy/test-drive/index.aspx["NetApp 시험 구동"^] 즉시 사용 가능한 랩 이미지 사용 테스트 드라이브는 3노드 Kubernetes 클러스터와 Astra Trident가 설치 및 구성된 샌드박스 환경을 제공합니다. Astra Trident에 대해 알아보고 해당 기능을 살펴볼 수 있는 좋은 방법입니다.

또 다른 옵션은 입니다 link:https://kubernetes.io/docs/setup/independent/install-kubeadm/["kubeadm 설치 가이드"] Kubernetes에서 제공:


NOTE: 운영 환경에서는 이러한 지침에 따라 구축한 Kubernetes 클러스터를 사용하지 마십시오. 운영 가능 클러스터에 대해 배포에서 제공하는 운영 구축 가이드를 사용하십시오.



== 를 참조하십시오

* https://docs.netapp.com/us-en/astra-family/intro-family.html["NetApp Astra 제품군"^]
* https://docs.netapp.com/us-en/astra/get-started/intro.html["Astra Control Service 문서"^]
* https://docs.netapp.com/us-en/astra-control-center/index.html["Astra Control Center 문서"^]
* https://docs.netapp.com/us-en/astra-automation/get-started/before_get_started.html["Astra API 설명서"^]

