---
sidebar: sidebar 
permalink: trident-get-started/kubernetes-deploy-helm-mirror.html 
keywords: deploy, astra trident, operator, helm, helm chart, configuration, values, offline, air gap, gap, registry 
summary: Trident 연산자를 구축하고 Hrom을 사용하여 Astra Trident를 설치할 수 있습니다. 이 프로세스는 Astra Trident에 필요한 컨테이너 이미지가 개인 레지스트리에 저장된 설치에 적용됩니다. 
---
= H제어(오프라인 모드)를 사용하여 Trident 연산자 배포
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Trident 연산자를 구축하고 Hrom을 사용하여 Astra Trident를 설치할 수 있습니다. 이 프로세스는 Astra Trident에 필요한 컨테이너 이미지가 개인 레지스트리에 저장된 설치에 적용됩니다. 개인 이미지 레지스트리가 없는 경우 를 사용합니다 link:kubernetes-deploy-helm.html["표준 배포 프로세스"].



== Astra Trident 23.01에 대한 중요 정보입니다

* Astra Trident * 에 대한 다음 중요 정보를 읽어야 합니다

.<strong> 중요 정보 Astra Trident </strong>
[%collapsible%open]
====
* 이제 Trident에서 Kubernetes 1.26이 지원됩니다. Kubernetes를 업그레이드하기 전에 Trident를 업그레이드하십시오.
* Astra Trident는 SAN 환경에서 다중 경로 구성을 엄격하게 사용하며 권장 값은 입니다 `find_multipaths: no` 다중 경로 .conf 파일
+
비 경로 다중화 구성 또는 의 사용 `find_multipaths: yes` 또는 `find_multipaths: smart` multipath.conf 파일의 값으로 인해 마운트 오류가 발생합니다. Trident에서 의 사용을 권장했습니다 `find_multipaths: no` 21.07 릴리스 이후.



====


== Trident 연산자를 구축하고 Hrom을 사용하여 Astra Trident를 설치합니다

Trident 사용 link:https://artifacthub.io/packages/helm/netapp-trident/trident-operator["Helm 차트"^] Trident 연산자를 구축하고 Trident를 한 번에 설치할 수 있습니다.

검토 link:../trident-get-started/kubernetes-deploy.html["설치 개요"] 설치 사전 요구 사항을 충족하고 환경에 맞는 올바른 설치 옵션을 선택했는지 확인합니다.

.시작하기 전에
또한 link:../trident-get-started/kubernetes-deploy.html#before-you-deploy["구축 사전 요구 사항"] 필요한 것입니다 link:https://v3.helm.sh/["Helm 버전 3"^].

.단계
. Astra Trident Helm 리포지토리를 추가합니다.
+
[listing]
----
helm repo add netapp-trident https://netapp.github.io/trident-helm-chart
----
. 사용 `helm install` 배포 및 이미지 레지스트리 위치의 이름을 지정합니다. 귀사의 link:../trident-get-started/requirements.html#container-images-and-corresponding-kubernetes-versions["Trident 및 CSI 이미지"] 하나의 레지스트리 또는 다른 레지스트리에 있을 수 있지만 모든 CSI 이미지는 동일한 레지스트리에 있어야 합니다. 예를 들어, `23.01.1` 는 설치 중인 Astra Trident의 버전입니다.
+
[role="tabbed-block"]
====
.하나의 레지스트리에 있는 이미지
--
[listing]
----
helm install <name> netapp-trident/trident-operator --version 23.01.1 --set imageRegistry=<your-registry> --create-namespace --namespace <trident-namespace>
----
--
.다른 레지스트리의 이미지
--
추가해야 합니다 `sig-storage` 를 누릅니다 `imageRegistry` 다른 레지스트리 위치를 사용합니다.

[listing]
----
helm install <name> netapp-trident/trident-operator --version 23.01.1 --set imageRegistry=<your-registry>/sig-storage --set operatorImage=<your-registry>/netapp/trident-operator:23.01.1 --set tridentAutosupportImage=<your-registry>/netapp/trident-autosupport:23.01 --set tridentImage=<your-registry>/netapp/trident:23.01.1 --create-namespace --namespace <trident-namespace>
----
--
====
+

NOTE: Trident에 대한 네임스페이스를 이미 만든 경우에는 '--create-namespace' 매개 변수가 추가 네임스페이스를 만들지 않습니다.



을 사용할 수 있습니다 `helm list` 이름, 네임스페이스, 차트, 상태, 앱 버전과 같은 설치 세부 정보를 검토하려면 수정본 번호.



== 설치 중에 구성 데이터를 전달합니다

설치 중에 구성 데이터를 전달하는 방법에는 두 가지가 있습니다.

[cols="2"]
|===
| 옵션을 선택합니다 | 설명 


| `--values` (또는 `-f`)  a| 
재정의가 있는 YAML 파일을 지정합니다. 이 옵션은 여러 번 지정할 수 있으며 가장 오른쪽 파일이 우선 적용됩니다.



| `--set`  a| 
명령줄에 overrides를 지정합니다.

|===
예를 들어, 의 기본값을 변경합니다 `debug`에서 다음을 실행합니다 `--set` 명령 위치 `23.01.1` 설치 중인 Astra Trident의 버전입니다.

[listing]
----
helm install <name> netapp-trident/trident-operator --version 23.01.1  --create-namespace --namespace --set tridentDebug=true
----

NOTE: 제어 차트의 일부인 Values.YAML 파일은 키 목록과 기본값을 제공합니다.



== 다음 단계

이제 가능합니다 link:kubernetes-postdeployment.html["백엔드 및 스토리지 클래스를 생성하고, 볼륨을 프로비저닝하고, POD에 볼륨을 마운트합니다"].
