---
sidebar: sidebar 
permalink: trident-concepts/ontap-drivers.html 
keywords: trident backend, AFF, FAS, ONTAP Select, Cloud, Amazon FSx for NetApp ONTAP, drivers, ONTAP drivers 
summary: Trident 설치에서 Element 백엔드를 만들고 사용하는 방법에 대해 알아보십시오. 
---
= ONTAP 드라이버
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Astra Trident는 ONTAP 클러스터와 통신할 수 있도록 5개의 고유한 ONTAP 스토리지 드라이버를 제공합니다. 각 드라이버가 볼륨 생성, 액세스 제어 및 해당 기능을 처리하는 방법에 대해 자세히 알아보십시오.



== ONTAP 스토리지 드라이버에 대해 알아보십시오


WARNING: 고객은 을 사용해야 합니다 `ontap-nas` 데이터 보호, 재해 복구 및 이동성을 필요로 하는 운영 워크로드를 위한 추진 요인 Astra Control은 로 생성된 볼륨에 대해 원활한 보호, 재해 복구 및 이동성을 제공합니다 `ontap-nas` 드라이버. 를 클릭합니다 `ontap-nas-economy` 예상 볼륨 사용이 ONTAP에서 지원하는 것보다 훨씬 높을 것으로 예상되는 제한적인 사용 사례에서 드라이버를 사용해야 하며, 예상되는 데이터 보호, 재해 복구 또는 이동성(Kubernetes 클러스터 간 볼륨 이동) 요구사항은 없습니다.

[cols="5"]
|===
| 드라이버 | 프로토콜 | 볼륨 모드 | 액세스 모드가 지원됩니다 | 지원되는 파일 시스템 


| 'ONTAP-NAS'  a| 
NFS 를 참조하십시오
 a| 
파일 시스템
 a| 
RWO, ROX, rwx
 a| 
"", NFS



| ONTAP-NAS-이코노미  a| 
NFS 를 참조하십시오
 a| 
파일 시스템
 a| 
RWO, ROX, rwx
 a| 
"", NFS



| 'ONTAP-NAS-Flexgroup'  a| 
NFS 를 참조하십시오
 a| 
파일 시스템
 a| 
RWO, ROX, rwx
 a| 
"", NFS



| 'ONTAP-SAN'  a| 
iSCSI
 a| 
블록
 a| 
RWO, ROX, rwx
 a| 
파일 시스템이 없습니다. 원시 블록 디바이스입니다



| 'ONTAP-SAN'  a| 
iSCSI
 a| 
파일 시스템
 a| 
RWO, ROX

파일 시스템 볼륨 모드에서는 rwx를 사용할 수 없습니다.
 a| 
xfs, ext3, ext4



| ONTAP-SAN-이코노미  a| 
iSCSI
 a| 
블록
 a| 
RWO, ROX, rwx
 a| 
파일 시스템이 없습니다. 원시 블록 디바이스입니다



| ONTAP-SAN-이코노미  a| 
iSCSI
 a| 
파일 시스템
 a| 
RWO, ROX

파일 시스템 볼륨 모드에서는 rwx를 사용할 수 없습니다.
 a| 
xfs, ext3, ext4

|===

NOTE: ONTAP 백엔드는 보안 역할(사용자 이름/암호)에 대한 로그인 자격 증명을 사용하거나 ONTAP 클러스터에 설치된 개인 키와 인증서를 사용하여 인증할 수 있습니다. 기존 백엔드를 업데이트하여 를 사용하여 한 인증 모드에서 다른 인증 모드로 이동할 수 있습니다 `tridentctl update backend`.
