---
sidebar: sidebar 
permalink: trident-reference/rest-api.html 
keywords: rest api, get, post, json, object, backends 
summary: Astra Trident의 REST API와 상호 작용하려는 경우 REST 엔드포인트를 직접 사용할 수 있습니다. 
---
= Astra Trident REST API
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
있습니다 link:tridentctl.html["tridentctl 명령 및 옵션"^] 는 Astra Trident의 REST API와 상호 작용하는 가장 쉬운 방법이며, 원할 경우 REST 엔드포인트를 직접 사용할 수 있습니다.

이 기능은 Kubernetes가 아닌 구축 환경에서 Astra Trident를 독립 실행형 바이너리로 사용하는 고급 설치에 유용합니다.

보안을 강화하기 위해 POD 내부에서 실행할 때 Astra Trident의 'ReST API'는 기본적으로 localhost로 제한됩니다. 이 동작을 변경하려면 POD 구성에서 Astra Trident의 '-address' 인수를 설정해야 합니다.

API는 다음과 같이 작동합니다.



== 가져오기

* '<triment-address>/triment/v1/<object-type>': 해당 형식의 모든 개체를 나열합니다.
* '<trident-address>/trident/v1/<object-type>/<object-name>': 명명된 개체의 세부 정보를 가져옵니다.




== 게시

'<triment-address>/triment/v1/<object-type>': 지정된 형식의 개체를 만듭니다.

* 생성할 개체의 JSON 구성이 필요합니다. 각 개체 유형의 사양은 을 참조하십시오 link:tridentctl.html["ce87eb03803d5633c163541464e9e7f2"].
* 개체가 이미 있는 경우 동작이 달라집니다. backends는 기존 개체를 업데이트하지만 다른 모든 개체 형식은 작업에 실패합니다.




== 삭제

삭제 <triment-address>/triment/v1/<object-type>/<object-name>': 명명된 리소스를 삭제합니다.


NOTE: 백엔드 또는 스토리지 클래스와 연결된 볼륨은 계속 존재하므로 별도로 삭제해야 합니다. 자세한 내용은 을 참조하십시오 link:tridentctl.html["ce87eb03803d5633c163541464e9e7f2"].

이러한 API의 호출 방법에 대한 예제를 보려면 debug("-d") 플래그를 전달하십시오. 자세한 내용은 을 참조하십시오 link:tridentctl.html["ce87eb03803d5633c163541464e9e7f2"].
