---
sidebar: sidebar 
permalink: trident-reference/tridentctl.html 
keywords: tridentctl, trident, kubernetes, commands, options, usage, flags 
summary: Trident에 대한 간단한 액세스를 제공하는 명령줄 유틸리티인 tridentctl 에 대해 자세히 알아보십시오. 
---
= tridentctl 명령 및 옵션
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
를 클릭합니다 https://["Trident 설치 프로그램 번들"^] Astra Trident에 대한 간단한 액세스를 제공하는 명령줄 유틸리티인 tridentctl이 포함되어 있습니다. 충분한 권한을 가진 Kubernetes 사용자는 이를 사용하여 Astra Trident를 설치할 뿐 아니라 직접 상호 작용하여 Astra Trident Pod가 포함된 네임스페이스를 관리할 수 있습니다.



== 사용 가능한 명령 및 옵션

사용법은 tridentctl - -help를 실행한다.

사용 가능한 명령 및 전역 옵션은 다음과 같습니다.

[listing]
----
Usage:
  tridentctl [command]
----
사용 가능한 명령:

* 'create': Astra Trident에 리소스를 추가합니다.
* 삭제: Astra Trident에서 하나 이상의 리소스를 제거합니다.
* 'Get': Astra Trident에서 하나 이상의 리소스를 받아보세요.
* 도움말 : 명령에 대한 도움말입니다.
* "이미지": Astra Trident가 필요로 하는 컨테이너 이미지 테이블을 인쇄합니다.
* 가져오기: 기존 자원을 Astra Trident로 가져옵니다.
* 설치: Astra Trident 설치
* 로그: 아스트라 트리덴트(Astra Trident)의 로그를 인쇄합니다.
* '종료': Astra Trident에서 리소스를 보냅니다.
* "설치 제거": Astra Trident를 제거합니다.
* 업데이트: Astra Trident에서 자원을 수정합니다.
* 업그레이드: Astra Trident에서 리소스를 업그레이드합니다.
* '러션': 아스트라 트리덴트(Astra Trident)의 버전을 인쇄해 보세요.


플래그:

* ''-d,--debug': 출력 디버그
* ''-h,- 도움말: tridentctl 도움말.
* ''-n,-namespace string': Astra Trident 배포의 네임스페이스.
* ''-o, - 출력 문자열: 출력 형식. json|YAML|name|wide|ps(기본값) 중 하나.
* ``s’, -- 서버 문자열: Astra Trident REST 인터페이스의 주소/포트.
+

CAUTION: Trident REST 인터페이스는 127.0.0.1(IPv4의 경우) 또는 [::1](IPv6의 경우)에서만 수신 및 서비스하도록 구성할 수 있습니다.




CAUTION: Trident REST 인터페이스는 127.0.0.1(IPv4의 경우) 또는 [::1](IPv6의 경우)에서만 수신 및 서비스하도록 구성할 수 있습니다.



== `create`

'create' 명령을 실행하여 Astra Trident에 리소스를 추가할 수 있습니다.

[listing]
----
Usage:
  tridentctl create [option]
----
사용 가능한 옵션: "backend": Astra Trident에 백엔드를 추가합니다.



== `delete`

"Delete" 명령을 실행하여 Astra Trident에서 하나 이상의 리소스를 제거할 수 있습니다.

[listing]
----
Usage:
  tridentctl delete [option]
----
사용 가능한 옵션:

* 백엔드: Astra Trident에서 하나 이상의 스토리지 백엔드를 삭제합니다.
* '스냅샷': Astra Trident에서 하나 이상의 볼륨 스냅샷을 삭제합니다.
* '스토라게': 아스트라 트리덴트(Astra Trident)에서 하나 이상의 스토리지 클래스를 삭제합니다.
* '볼륨': Astra Trident에서 하나 이상의 스토리지 볼륨을 삭제합니다.




== `get`

"get" 명령을 실행하여 Astra Trident에서 하나 이상의 리소스를 가져올 수 있습니다.

[listing]
----
Usage:
  tridentctl get [option]
----
사용 가능한 옵션:

* "백엔드": Astra Trident에서 하나 이상의 스토리지 백엔드를 가져옵니다.
* 스냅샷: 아스트라 트리덴트(Astra Trident)에서 하나 이상의 스냅샷을 얻을 수 있습니다.
* '스라거글라스': 아스트라 트리덴트(Astra Trident)에서 하나 이상의 스토리지 클래스를 받으세요.
* '볼륨': 아스트라 트리덴트(Astra Trident)에서 하나 이상의 볼륨을 가져옵니다.


`volume` 플래그: * ``-h, --help`: 볼륨에 대한 도움말입니다. * `--parentOfSubordinate string`: 하위 원본 볼륨으로 쿼리를 제한합니다. * `--subordinateOf string`: 볼륨 부하로 쿼리 제한.



== `images`

"images" 플래그를 실행하여 Astra Trident에 필요한 컨테이너 이미지 테이블을 인쇄할 수 있습니다.

[listing]
----
Usage:
  tridentctl images [flags]
----
플래그: * ``h, - 도움말’: 이미지 도움말. * ``v, - -k8s-version string': Kubernetes 클러스터의 의미 있는 버전



== `import volume`

'볼륨 가져오기' 명령을 실행하여 기존 볼륨을 Astra Trident로 가져올 수 있습니다.

[listing]
----
Usage:
  tridentctl import volume <backendName> <volumeName> [flags]
----
별칭: 볼륨, v

플래그:

* ''-f, --파일 이름 문자열': YAML 또는 JSON PVC 파일 경로.
* ''-h, - 도움말: 볼륨 도움말.
* '--관리 안 함: PV/PVC만 생성 볼륨 라이프사이클 관리를 가정하지 마십시오.




== `install`

설치 플래그를 실행하여 Astra Trident를 설치할 수 있습니다.

[listing]
----
Usage:
  tridentctl install [flags]
----
플래그:

* "--autosupport-image string": AutoSupport Telemetry의 컨테이너 이미지(기본값: "NetApp/트리덴트 자동 지원: 20.07.0")
* `--autosupport-proxy string': AutoSupport 텔레메트리 전송을 위한 프록시의 주소/포트입니다.
* "--CSI": CSI Trident 설치(Kubernetes 1.13의 경우에만 재정의, 기능 게이트 필요)
* ''--enable-node-prep': 노드에 필요한 패키지 설치 시도
* ''--generate-custom-YAML': 아무것도 설치하지 않고 YAML 파일을 생성합니다.
* ''-h, - 도움말: 설치 도움말.
* `--http-request-timeout': Trident 컨트롤러의 REST API에 대한 HTTP 요청 시간 초과를 재정의합니다(기본값 1m30s).
* ''--image-registry string': 내부 이미지 레지스트리의 주소/포트입니다.
* ''--k8s-timeout duration': 모든 Kubernetes 운영(기본값 3m0s)의 시간 초과.
* ''--kubelet-dir string': kubelet의 내부 상태(기본값 "/var/lib/kubelet")의 호스트 위치입니다.
* ''--log-format string': Astra Trident 로깅 형식(text, json)(기본 "text").
* `--pv string ': Astra Trident가 사용한 레거시 PV의 이름이며, 이 이름이 존재하지 않는지 확인합니다(기본 "삼중류").
* ''--PVC string': Astra Trident에서 사용하는 기존 PVC의 이름인 경우 이 항목이 존재하지 않는지 확인합니다(기본 "삼중류").
* ``침묵 AutoSupport’’는 AutoSupport 번들을 NetApp에 자동으로 보내지 않습니다(기본값: TRUE).
* '--silent': 설치 중 대부분의 출력을 비활성화합니다.
* '--trident-image string': 설치할 Astra Trident 이미지.
* ''--use-custom-YAML': 설정 디렉토리에 존재하는 기존 YAML 파일을 사용합니다.
* ''--use-ipv6: Astra Trident의 통신에는 IPv6를 사용합니다.




== `logs`

"logs" 플래그를 실행하여 Astra Trident의 로그를 인쇄할 수 있습니다.

[listing]
----
Usage:
  tridentctl logs [flags]
----
플래그:

* ``A, - 아카이브' : 달리 명시하지 않는 한 모든 로그를 포함하는 지원 아카이브를 만듭니다.
* ''-h, - 도움말: 로그 도움말.
* ''-l,-log string': Astra Trident log를 표시합니다. 트리덴트|auto|트리덴트-operator|all 중 하나(기본 "자동").
* ''--node string: 노드 POD 로그를 수집할 Kubernetes 노드 이름입니다.
* ''-p, -- previous': 이전 컨테이너 인스턴스에 대한 로그가 있으면 가져옵니다.
* '--사이드카': 사이드카 컨테이너의 통나무를 가져오십시오.




== `send`

'send' 명령을 실행하여 Astra Trident에서 리소스를 보낼 수 있습니다.

[listing]
----
Usage:
  tridentctl send [option]
----
사용 가능한 옵션: 'AutoSupport': AutoSupport 아카이브를 NetApp에 보냅니다.



== "제거"를 선택합니다

"uninstall" 플래그를 실행하여 Astra Trident를 제거할 수 있습니다.

[listing]
----
Usage:
  tridentctl uninstall [flags]
----
플래그: * `-h, --help`: 제거 도움말입니다. * `--silent`: 제거 중 대부분의 출력을 비활성화합니다.



== `update`

'update' 명령어를 실행하여 Astra Trident에서 자원을 수정할 수 있다.

[listing]
----
Usage:
  tridentctl update [option]
----
사용 가능한 옵션: "backend": Astra Trident에서 백엔드를 업데이트합니다.



== `upgrade`

"업그레이드" 명령을 실행하여 Astra Trident에서 리소스를 업그레이드할 수 있습니다.

[listing]
----
Usage:
tridentctl upgrade [option]
----
사용 가능한 옵션: 볼륨: NFS/iSCSI에서 CSI로 하나 이상의 영구 볼륨을 업그레이드합니다.



== '내전'

'tridentctl' 및 실행 중인 Trident 서비스의 버전을 인쇄하려면 'rsion' 플래그를 실행할 수 있습니다.

[listing]
----
Usage:
  tridentctl version [flags]
----
플래그: * `--client': 클라이언트 버전만 해당(서버 필요 없음). '-h, - 도움말': 버전 도움말.
