---
sidebar: sidebar 
permalink: trident-reference/tridentctl.html 
keywords: tridentctl, trident, kubernetes, commands, options, usage, flags 
summary: Trident에 대한 간단한 액세스를 제공하는 명령줄 유틸리티인 tridentctl 에 대해 자세히 알아보십시오. 
---
= tridentctl을 사용하여 Astra Trident를 관리합니다
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
를 클릭합니다 https://github.com/NetApp/trident/releases["Trident 설치 프로그램 번들"^] 에는 가 포함되어 있습니다 `tridentctl` Astra Trident에 대한 간단한 액세스를 제공하는 명령줄 유틸리티 충분한 권한을 가진 Kubernetes 사용자는 Astra Trident를 설치하거나 Astra Trident Pod가 포함된 네임스페이스를 관리하는 데 사용할 수 있습니다.



== 명령 및 글로벌 플래그

실행할 수 있습니다 `tridentctl help` 에 사용할 수 있는 명령 목록을 가져옵니다 `tridentctl` 또는 를 추가합니다 `--help` 특정 명령에 대한 옵션 및 플래그 목록을 가져오려면 임의의 명령에 플래그를 지정합니다.

사용::


[listing]
----
tridentctl [command] [--optional-flag]
----
Astra Trident를 소개합니다 `tridentctl` 유틸리티는 다음 명령 및 글로벌 플래그를 지원합니다.

.명령
[%collapsible]
====
`create`:: Astra Trident에 리소스를 추가합니다.
`delete`:: Astra Trident에서 하나 이상의 리소스를 제거하십시오.
`get`:: Astra Trident에서 하나 이상의 리소스를 확인하십시오.
`help`:: 모든 명령에 대한 도움말.
`images`:: Astra Trident가 필요한 컨테이너 이미지 표를 인쇄합니다.
`import`:: 기존 리소스를 Astra Trident로 임포트합니다.
`install`:: Astra Trident를 설치합니다.
`logs`:: Astra Trident에서 로그를 인쇄합니다.
`send`:: Astra Trident에서 리소스를 전송합니다.
"제거"를 선택합니다:: Astra Trident를 제거합니다.
`update`:: Astra Trident에서 리소스를 수정합니다.
`update backend state`:: 백엔드 작업을 일시적으로 중단합니다.
`upgrade`:: Astra Trident에서 리소스를 업그레이드합니다.
'내전':: Astra Trident 버전을 인쇄하십시오.


====
.글로벌 플래그
[%collapsible]
====
`-d`, `--debug`:: 디버그 출력.
`-h`, `--help`:: 도움말 `tridentctl`.
`-n`, `--namespace string`:: Astra Trident 구축의 네임스페이스
`-o`, `--output string`:: 출력 형식. json|YAML|name|wide|ps(기본값) 중 하나.
`-s`, `--server string`:: Astra Trident REST 인터페이스의 주소/포트
+
--

WARNING: Trident REST 인터페이스는 127.0.0.1(IPv4의 경우) 또는 [::1](IPv6의 경우)에서만 수신 및 서비스하도록 구성할 수 있습니다.

--


====


== 명령 옵션 및 플래그



=== `create`

를 사용합니다 `create` Astra Trident에 리소스를 추가하는 명령입니다.

사용::


[listing]
----
tridentctl create [option]
----
옵션:: Astra Trident에 백엔드를 추가한다.




=== `delete`

를 사용합니다 `delete` Astra Trident에서 하나 이상의 리소스를 제거하는 명령입니다.

사용::


[listing]
----
tridentctl delete [option]
----
옵션:: Astra Trident에서 스토리지 백엔드를 하나 이상 삭제합니다.
`snapshot`:: Astra Trident에서 볼륨 스냅샷을 하나 이상 삭제합니다.
`storageclass`:: Astra Trident에서 하나 이상의 스토리지 클래스를 삭제합니다.
`volume`:: Astra Trident에서 하나 이상의 스토리지 볼륨을 삭제합니다.




=== `get`

를 사용합니다 `get` Astra Trident에서 하나 이상의 리소스를 제공하는 명령입니다.

사용::


[listing]
----
tridentctl get [option]
----
옵션:: Astra Trident에서 하나 이상의 스토리지 백엔드를 활용해 보십시오.
`snapshot`:: Astra Trident에서 하나 이상의 스냅샷을 생성하십시오.
`storageclass`:: Astra Trident에서 하나 이상의 스토리지 클래스를 이용하세요.
`volume`:: Astra Trident에서 하나 이상의 볼륨을 생성하십시오.
깃발:: 볼륨 도움말.
`--parentOfSubordinate string`:: 하위 소스 볼륨으로 쿼리를 제한합니다.
`--subordinateOf string`:: 쿼리를 볼륨의 부하로 제한합니다.




=== `images`

사용 `images` Astra Trident에 필요한 컨테이너 이미지 표를 인쇄하기 위한 플래그

사용::


[listing]
----
tridentctl images [flags]
----
깃발:: 이미지 도움말.
`-v`, `--k8s-version string`:: Kubernetes 클러스터의 시맨틱 버전




=== `import volume`

를 사용합니다 `import volume` 기존 볼륨을 Astra Trident로 가져오는 명령입니다.

사용::


[listing]
----
tridentctl import volume <backendName> <volumeName> [flags]
----
별칭:: `volume, v`
깃발:: YAML 또는 JSON PVC 파일의 경로입니다.
`-h`, `--help`:: 볼륨 도움말.
`--no-manage`:: PV/PVC만 생성합니다. 볼륨 라이프사이클 관리를 가정하지 마십시오.




=== `install`

를 사용합니다 `install` Astra Trident를 설치하는 플래그입니다.

사용::


[listing]
----
tridentctl install [flags]
----
깃발:: AutoSupport 원격 측정의 컨테이너 이미지(기본값 "NetApp/trident autosupport:<current-version>")
`--autosupport-proxy string`:: AutoSupport 원격 분석을 보내는 프록시의 주소/포트입니다.
`--enable-node-prep`:: 노드에 필요한 패키지를 설치해 봅니다.
`--generate-custom-yaml`:: 아무것도 설치하지 않고 YAML 파일을 생성합니다.
`-h`, `--help`:: 설치 도움말.
`--http-request-timeout`:: Trident 컨트롤러의 REST API에 대한 HTTP 요청 시간 초과를 재정의합니다(기본값 1m30s).
`--image-registry string`:: 내부 이미지 레지스트리의 주소/포트입니다.
`--k8s-timeout duration`:: 모든 Kubernetes 작업에서 시간 초과(기본값 3m0s).
`--kubelet-dir string`:: kubelet의 내부 상태의 호스트 위치(기본값 "/var/lib/kubelet")
`--log-format string`:: Astra Trident 로깅 형식(text, json)(기본 "text")
`--pv string`:: Astra Trident에서 사용하는 기존 PV의 이름은 이 이름이 존재하지 않는지 확인합니다(기본 "트라이덴트").
`--pvc string`:: Astra Trident에서 사용하는 기존 PVC의 이름은 이것이 존재하지 않는지 확인합니다(기본 "트라이덴트").
`--silence-autosupport`:: AutoSupport 번들을 NetApp에 자동으로 보내지 않습니다(기본값 true).
`--silent`:: 설치 중에 MOST 출력을 비활성화합니다.
`--trident-image string`:: 설치할 Astra Trident 이미지
`--use-custom-yaml`:: 설치 디렉터리에 있는 기존 YAML 파일을 사용합니다.
`--use-ipv6`:: Astra Trident의 통신에 IPv6 사용




=== `logs`

사용 `logs` Astra Trident의 로그를 인쇄할 플래그입니다.

사용::


[listing]
----
tridentctl logs [flags]
----
깃발:: 별도로 지정하지 않는 한 모든 로그를 사용하여 지원 아카이브를 생성합니다.
`-h`, `--help`:: 로그 도움말.
`-l`, `--log string`:: Astra Trident 로그가 표시됩니다. 트리덴트|auto|트리덴트-operator|all 중 하나(기본 "자동").
`--node string`:: 노드 Pod 로그를 수집할 Kubernetes 노드 이름입니다.
`-p`, `--previous`:: 이전 컨테이너 인스턴스가 있는 경우 로그를 가져옵니다.
`--sidecars`:: 사이드카 컨테이너의 로그를 가져옵니다.




=== `send`

를 사용합니다 `send` Astra Trident에서 리소스를 보내는 명령입니다.

사용::


[listing]
----
tridentctl send [option]
----
옵션:: AutoSupport 아카이브를 NetApp로 전송합니다.




=== "제거"를 선택합니다

사용 `uninstall` Astra Trident를 제거하는 플래그입니다.

사용::


[listing]
----
tridentctl uninstall [flags]
----
깃발:: 제거 도움말.
`--silent`:: 제거 중 MOST 출력을 비활성화합니다.




=== `update`

를 사용합니다 `update` Astra Trident에서 리소스를 수정하는 명령

사용::


[listing]
----
tridentctl update [option]
----
옵션:: Astra Trident에서 백엔드를 업데이트합니다.




=== `update backend state`

를 사용합니다 `update backend state` 백엔드 작업을 일시 중지하거나 재개하는 명령입니다.

사용::


[listing]
----
tridentctl update backend state <backend-name> [flag]
----
깃발:: 를 로 설정합니다 `suspended` 백엔드 작업을 일시 중지합니다. 를 로 설정합니다 `normal` 백엔드 작업을 재개합니다. 를 로 설정한 경우 `suspended`:
+
--
* `AddVolume`, `CloneVolume`, `Import Volume`, `ResizeVolume` 일시 중지되었습니다.
* `PublishVolume`, `UnPublishVolume`, `CreateSnapshot`, `GetSnapshot`, `RestoreSnapshot`, `DeleteSnapshot`, `RemoveVolume`, `GetVolumeExternal`, `ReconcileNodeAccess` 사용 가능 상태를 유지합니다.


--
`-h`, `--help`:: 백엔드 상태에 대한 도움말입니다.




=== '내전'

사용 `version` 플래그를 사용하여 의 버전을 인쇄합니다 `tridentctl` 및 실행 중인 Trident 서비스를 제공합니다.

사용::


[listing]
----
tridentctl version [flags]
----
깃발:: 클라이언트 버전만 해당(서버가 필요하지 않음).
`-h, --help`:: 버전에 대한 도움말입니다.

